### PR TITLE
removed explicit return statements

### PR DESCRIPTION
**Pull request by ojss**
I have removed the explicit returns. Please take a look.

**Unable to test, because Last.fm is blocked by uni**

### CODE REVIEW

**Comment by ojss** [comment]
@trmml did you test it before merging?

**Comment by trmml** [comment]
Yeah, everything works fine, except explicit returning was necessary in `hash.rb`. I merged, pulled, and fixed the problem. Thanks! :+1:

**Comment by ojss** [comment]
Yeah I just realised it after you merged. really sorry about it. I am kind of sick so I failed to pay attention to that. :smile:

**Comment by trmml** [comment]
no worries! thanks for the PR, get well soon :smile_cat:

**Pull request merged**
